### ISSUE TITLE
YouTube subscriptions are in CSV instead of JSON

### ISSUE THREAD

**Issue by johnfocker** [iv-org/documentation#159] opened 2021-10-30 09:55 UTC
When following instructions to export YouTube subscriptions here:
[Export-YouTube-subscriptions.md](https://github.com/iv-org/documentation/blob/master/Export-YouTube-subscriptions.md)

I end up with a `subscriptions.csv` file that the instance I'm using can't seem to parse.

Instance is on `Current version: 2021.10.26-6a15b0b @ master`

**Comment by unixfox** [comment] 2021-10-30 18:53
Duplicate of https://github.com/iv-org/invidious/issues/2319

**Closed by unixfox** 2021-10-30 18:53 UTC
